global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 1m

scrape_configs:        

  - job_name: node
    scrape_interval: 3s
    scrape_timeout: 3s  
    static_configs:
      - targets:
          - prometheus-node-exporter:9100

  - job_name: clickhouse
    scrape_interval: 3s
    scrape_timeout: 3s   
    static_configs:
      - targets:
          - clickhouse:9363
